.gitignore, release.sh
La procédure pour déployer une nouvelle version de DORA en production est aujourd'hui effectuée manuellement.
Ça engendre : 
* de la complication
* du temps (celui de se souvenir des manipulations et de tout vérifier)
* des messages de mise en production non homogènes
* des risques d'erreurs de manipulation
* du stress
Automatiser la procédure de mise en production.
```shell
./release.sh back && ./release.sh front
```
Subtilité : on réalise le tout dans un répertoire temporaire.
Ce script est un MVP, le plus basique possible, qui se contente de gérer les "cas autoroute" (normalement, 95% du temps).
Il ne demande qu'à être éprouvé et amélioré.
=> chore: add script to automatically push a new release into production

back/dora/services/search.py
**Problème :** DI fournit 2 services dont le champ `thematiques` a pour valeur `null`. Dans `_get_di_results()`, on considérait que c'était toujours une liste, provoquant ainsi une exception `TypeError` lors d'une recherche faisant ressortir ces services.
**Solution :** prise en compte de la nullité possible du champ `thematiques`.
**Recherches en erreur ainsi réparées :**
- https://dora.inclusion.beta.gouv.fr/recherche?city=59350&cl=Lille%20(59)&l=Lille%20(59)
- https://dora.inclusion.beta.gouv.fr/recherche?city=31555&cl=Toulouse%20(31)&l=Toulouse%20(31)
=> [HOTFIX] _get_di_results(): gère le cas où le champ thematiques est nul

.gitignore, back/.gitignore, docs/adr/001-migrer-le-code-vers-un-monorepo.md
Récemment, nous avons eu une réflexion + discussion sur le passage d'un multirepo à un monorepo.
Cette PR propose de mettre en place la pratique (+ organisation) d'enregistrements de décision d'architecture, avec comme premier sujet la migration vers un monorepo.
=> docs: proposition d'ADR pour passer d'un multirepo (front + back) à un monorepo

front/src/lib/components/forms/fields/select-field.svelte, front/src/lib/components/inputs/select/select.svelte, front/src/lib/components/inputs/select/simple-autocomplete.svelte, front/src/lib/requests/structures.ts, front/src/lib/utils/misc.ts, front/src/routes/(modeles-services)/_common/fields-structure.svelte, front/src/routes/(modeles-services)/services/creer/+page.svelte, front/src/routes/(modeles-services)/services/creer/+page.ts, front/src/routes/(modeles-services)/services/service-edition-form.svelte
ℹ️ PR créée à partir de la PR originale https://github.com/gip-inclusion/dora-front/pull/458 suite à la création du [monorepo](https://github.com/gip-inclusion/dora/pull/8).
**Dépendance back :** https://github.com/gip-inclusion/dora-back/pull/397
**Problème :** la création d'un service depuis un modèle cause un appel au point d'API /structures/ qui liste toutes les structures de la base lorsqu'on est admin. La taille de la réponse atteint 5 Mo et provoque un gros ralentissement voire un plantage de la page.
**Solution :** ajout d'un paramètre de recherche textuel sur le nom de la structure pour limiter le nombre de résultats. Le front l'utilise avec 3 caractères minimum.
**Changements :**
- `getManagedStructure()` : ajout d'un paramètre de recherche textuel et utilisation du paramètre …
=> Recherche de structures par le nom pour les admins et managers

front/src/routes/recherche/+page.svelte
ℹ️ PR créée à partir de la PR originale https://github.com/gip-inclusion/dora-front/pull/464 suite à la création du [monorepo](https://github.com/gip-inclusion/dora/pull/8).
**Problème :** les utilisateurs ont tendance à ne pas être intéressé par les services à distance en général
**Solution :** on présélectionne le filtre de lieu d'accueil « En présentiel »
**Effet de bord non voulu :** si un utilisateur désélectionne le filtre de lieu d'accueil « En présentiel » (et qu'aucun autre filtre n'est sélectionné), et recharge la page ou transmet l'URL à une autre personne, le filtre de lieu d'accueil « En présentiel » sera resélectionné.
=> Page recherche: sélection par défaut du filtre de lieu d'accueil « En présentiel »

back/dora/services/tests/test_search.py
Fait suite au hotfix #32.
Ajout de deux tests unitaires.
Lors d'une recherche de services DI via la fonction `_get_di_results()` :
- les services dont le champ `thematiques` a la valeur `[]` (liste vide) sont bien retournés ;
- les services dont le champ `thematiques` a la valeur `null` sont bien retournés.
=> Tests unitaires recherche DI avec champ thematiques à [] et null

back/config/settings/base.py
Suite à la MEP de ProConnect et le petit soucis de correspondance d'algo lors de l'enregistrement, on peut désormais selectionner le type d'algo utilisé pour le décodage du payload OIDC (par défaut RS256)
=> Permet de sélectionner l'algorithme OIDC via var-env

front/src/routes/recherche/search-result.svelte
Si un service ne possède pas d'adresse, on affiche "null".
> 💡 D'après l'équipe data·inclusion, cela concerne 6% des données provenant de Soliguide.
Côté front, ne pas afficher l'adresse principale si elle n'est pas renseignée (de même qu'on gérait déjà si le champ `address2` n'existe pas).
La question de cacher tout bonnement les services n'ayant pas des données clean a été posée (@ikarius ).
La piste retenue est de se dire qu'il vaut mieux les afficher, car au pire, il y a les infos de contact.
Il faut faire une recherche sur Lille pour des services alimentaires : 
```
http://localhost:3000/recherche?cats=equipement-et-alimentation&city=59350&cl=Lille+%2859%29&l=Lille+%2859%29
```
=> bugfix: ne pas afficher l'adresse quand elle n'est pas renseignée

back/dora/oidc/views.py
Les anciens utilisateurs IC encore connectés rencontraient une erreur lors d'une déconnexion explicite.
Il est préférable d'avoir un log de WARNING, qui disparaitra au fil du temps.
=> Ajout de log pour une déconnexion IC

back/dora/notifications/tasks/tests/tests_users.py
À cause d'une erreur d'indentation, le test `test_simpler_manager_structure_moderation_task_should_trigger()` échoue le mercredi.
`should_trigger()` utilise la date du jour, il faut donc qu'il soit appelé dans le contexte `freeze_time("2024-10-14")`.
=> Correction d'un test de notification

back/config/settings/base.py, back/dora/oidc/__init__.py, back/dora/oidc/backends.py, back/dora/oidc/tests.py, back/dora/oidc/utils.py
Au début l'idée était de faire une toute petite `management command` permettant la déconnexion des utilisateurs.
Mais en voulant faire les choses proprement, il s'est avéré qu'il est nécessaire de modifier la structure du package `dora.oidc` pour, entre autre, en faire une app Django à part entière.
Pour ce faire : 
- le module contenant le backend d'identification est maintenant `dora.oidc.backends` ,
- on supprime `OIDCError` largement inutile.
Voilà en gros ce que fait cette première PR (1).
À suivre : 
- PR 2 : une modification de modélisation, qui sera dans la nouvelle app et permettra de lier directement utilisateurs et sessions
- PR 3 : la `management command` proprement dites (déjà écrite), qui permet d'effacer les tokens DRF **ET** les sessions correspondantes (c'est à ça que …
=> Ajout de 'dora.oidc` en tant qu'app Django

back/dora/oidc/backends.py
On considère qu'un ancien utilisateur a son e-mail automatiquement
validé si il se connecte via ProConnect.
Il s'agit d'un cas à la marge où certains anciens utilisateurs pouvait ne pas avoir validé leur e-mail.
=> Validité des e-mails des anciens utilisateurs

back/dora/sirene/management/commands/_backup.py, back/dora/sirene/management/commands/import_sirene.py
- utilisation d'un suffixe aléatoire : à généraliser
- déplacement des DDL dans le package des commandes : visibilité réduite
=> fix: correction du nommage des PK pour les tables de backup

back/dora/oidc/management/commands/force_users_logout.py
Au menu : 
- déconnexion forcée des utilisateurs, 
- quelques options de filtrage,
- suppression sélective des tokens DRF,
- suppression des sessions Django associées (le pourquoi de #55 )
=> Commande de déconnexion des utilisateurs

front/package-lock.json, front/package.json
La version de `@sveltejs/kit` 2.8.1 fait planter le front. Je la bloque à 2.8.0 pour résoudre le problème, en attendant de trouver ce qui doit être changé pour faire fonctionner la 2.8.1.
=> Correction du problème de dépendance qui fait planter le front

back/config/settings/base.py
Fixée à 12 heures en correspondance avec la durée des sessions de ProConnect.
=> Modification de la durée de vie des sessions Django

back/config/settings/prod.py
Relatif à https://trello.com/c/vvs4q4yW/260-fix-bug-labellisation-des-cd-bloquer-le-label-une-fois-corrig%C3%A9
Une erreur `TooManyFieldsSent` est levée quand le nombre de champs d'un formulaire est
trop élevé.
C'est le cas pour certaines structures dans l'admin. 
On peut augmenter (doubler présentement) le nombre de champs possibles dans un formulaire pour que tout rentre
dans l'ordre via le paramètre `DATA_UPLOAD_MAX_NUMBER_FIELDS`.
Voir :
https://docs.djangoproject.com/en/5.0/ref/settings/#data-upload-max-number-fields
=> fix: correction d'une erreur de validation dans l'admin

back/dora/services/serializers.py
Ces champs étaient présents dans le sérialiseur de service, mais pas celui de modèle. Or, les deux sont utilisés de la même manière. L'oubli de ces champs cause une erreur au chargement de la page d'un modèle.
Exemple : http://localhost:3000/modeles/nenettes-co-le-resea-aide-au-permis-et-pr-htxi
=> ServiceModelSerializer: ajout des champs funding_labels et funding_labels_display

back/dora/auth_links/views.py
Les liens magiques n'étant pas stockés, le suivi de leur utilisation n'est pas possible sans ajout de traces.
Pour rappel, les liens de connexion directe ne sont autorisés que pour les anciens utilisateurs Inclusion-Connect qui se sont connectés à DORA.
=> Log des connexions directes par lien

back/requirements/base.txt
avant que `dependabot` y retrouve ses petits ...
voir https://www.djangoproject.com/weblog/2024/dec/04/security-releases/
=> libs: MaJ vers Django 4.2.17

front/src/routes/(modeles-services)/services/[slug]/orienter/teaser.svelte
Retrait d'un bouton avec l'intitulé Inclusion-Connect dans la partie orientation.
Remplacé par le bouton de connection ProConnect
=> fix: retrait d'un bouton Inclusion-Connect oublié

front/src/lib/types.ts, front/src/routes/(modeles-services)/services/[slug]/orienter/demande/+page.svelte, front/src/routes/(modeles-services)/services/[slug]/orienter/demande/orientation-form.svelte, front/src/routes/(modeles-services)/services/[slug]/orienter/schema.ts
Si la même adresse e-mail est utilisée pour le référent et pour le bénéficiaire, une erreur est montrée.
Si l'option _Via le référent_ est cochée, l'adresse e-mail du bénéficiaire est forcée, sans erreur.
=> L'adresse e-mail du bénéficiaire doit être différente de celle du référent ou utiliser l'option Via le référent

back/dora/structures/admin.py
Dans Django Admin, en bas de la page d'une structure, la liste des demandes d'orientations en cours de modération est affichée avec le prénom, nom et adresse e-mail du bénéficiaire et du référent, le service et le motif. Pas de possibilité d'ajout ou de suppression d'objet.
=> [Modération] 3. Affichage des demandes d’orientation en cours de modération

back/dora/data_inclusion/mappings.py, back/dora/data_inclusion/tests.py
Si un service DI comporte le mode `completer-le-formulaire-dadhesion` et que le champ `formulaire_en_ligne` est nul, on remplace ce mode par le mode `formulaire-dora`.
=> Dérivation du mode d'orientation par formulaire Dora pour les services DI

front/src/lib/consts.ts, front/src/lib/utils/orientation.ts, front/src/routes/(modeles-services)/services/[slug]/orienter/demande/orientation-form.svelte, front/src/tests/utils/orientation/orientationContainsTestWords.test.ts, front/tsconfig.json
Si un mot parmi _test_, _truc_, _bidule_ est détecté dans les champs prénom, nom, email du référent ou du bénéficiaire, ou bien dans le champ motif, alors on affiche une notice erreur en bas du formulaire. Cette erreur ne bloque pas l'envoi du formulaire.
J'ai écrit des tests pour la fonction utilitaire.
J'ai modifié la configuration de TypeScript pour que l'autocomplétion fonctionne dans les fichiers de test.
=> Détection de mots de test dans le formulaire d'orientation

back/config/settings/base.py, back/config/settings/prod.py
Voir : 
- https://trello.com/c/vvs4q4yW/260-fix-bug-labellisation-des-cd-bloquer-le-label-une-fois-corrig%C3%A9
- https://trello.com/c/30LWF6Xq/311-label-savoie-non-fonctionnel
Certaines structures ont un nombre conséquent de membres et
d'invitations en cours, ce qui peut poser des problèmes lors de l'envoi
du formulaire de modification dans l'admin Django.
Plusieurs paramètres Django permettent de dimensionner les limitations
de ce qui est envoyé par formulaire au serveur.
Dans le cas présent : la valeur `DATA_UPLOAD_MAX_NUMBER_FIELDS` a été
doublée pour pouvoir modifier certaines structures sans erreurs.
Corrélée à : #91, le nombre d'éléments était insuffisant
=> fix: correction d'une erreur de formulaire dans l'admin

front/src/lib/components/specialized/services/display/service-duration.svelte, front/src/lib/components/specialized/services/fields-duration.svelte
Suite à la première démonstration de la fonctionnalité "Temps passé" (d'un service), des propositions d'amélioration UX / nommage ont été proposées.
Modifier les titres concernés.
=> feat(intensite-de-parcours): modification de titres / libellés

front/src/routes/(endpoints)/sitemap.xml/+server.ts
Erreur Sentry : https://sentry.gip-inclusion.org/organizations/gip-inclusion/issues/12195/?project=5&query=is%3Aunresolved&referrer=issue-stream&statsPeriod=14d&stream_index=0
La page `/sitemap.xml` charge l’ensemble des structures et des services, ce qui fait beaucoup trop de volume, surcharge le serveur et finit par planter.
Pour résoudre ce problème, j’ai supprimé purement le chargement de ces données.
=> fix: sitemap: ne charge plus tous les services et structures pour éviter plantage. Prise en compte de l'environnement dev.

back/dora/auth_links/enums.py, back/dora/auth_links/views.py
Relatif à : https://trello.com/c/wWLEviB6/308-tableaux-de-suivi-migration-pro-connect
Ajoute un champ `action` dans le corps des logs permettra de contruire un
tableau de suivi plus facilement (les actions relatives à la connexion
directe sont catégorisées).
=> Catégorisation des actions pour les connexions directes

.github/workflows/lint-pr.yml
On utilise [action-semantic-pull-request](https://github.com/amannn/action-semantic-pull-request). J'ai juste recopié la configuration proposée et traduit le nom de la tâche en français.
L'action ne sera déclenchée qu'une fois présente dans main dû à l'utilisation de [pull_request_target](https://docs.github.com/en/actions/reference/events-that-trigger-workflows#pull_request_target).
https://trello.com/c/3KDV7wMk/332-ci-ajout-dune-action-de-validation-du-titre-de-la-pr-action-semantic-pull-request
=> ci(pr): Ajout d'une action GitHub de validation du titre de la PR

front/src/lib/consts.ts, front/src/lib/requests/services.ts, front/src/lib/requests/structures.ts, front/src/lib/utils/date.ts, front/src/routes/(endpoints)/sitemap-services-[page].xml/+server.ts, front/src/routes/(endpoints)/sitemap-structures-[page].xml/+server.ts, front/src/routes/(endpoints)/sitemap.xml/+server.ts
https://trello.com/c/2MXHfwXs/323-g%C3%A9n%C3%A9ration-de-multiples-fichiers-sitemap-contenant-tous-les-services-et-toutes-les-structures
Documentation Google sur le fichier d'index de sitemaps : https://developers.google.com/search/docs/crawling-indexing/sitemaps/large-sitemaps?hl=fr
Les ViewSet DRF pour les structures et services supportaient déjà une pagination optionnelle. Je l'exploite pour paginer le sitemap.
Le chemin `/sitemap.xml` indexe les sous-sitemaps des services et structures.
Le chemin `/sitemap-services-[page].xml` affiche une page de sitemap pour les services.
Le chemin `/sitemap-structures-[page].xml` affiche une page de sitemap pour les structures.
J'ai enlevé le chemin statique `/contribuer` qui ne me semble pas utile car navigable naturellement.
J'ai supprimé le test …
=> fix(sitemap): Sitemap paginé

front/src/lib/components/specialized/services/display/service-duration.svelte, front/src/lib/components/specialized/services/display/service-key-informations.svelte
La section <ServiceDuration/> étant un nouveau composant, elle ne bénéficie pas des styles inline pour les éléments `p` défini dans son composant parent.
Ce commit permet de conserer le même comportement.
Avant : 
Après :
=> style: Uniformisation de taille de police

back/requirements/base.txt
Voir :
https://www.djangoproject.com/weblog/2025/jan/14/security-releases/
=> chore(deps): MaJ de Django vers la version 4.2.18

.github/dependabot.yml
Les PR générées par Dependabot sont préfxiées "requirement:" ce qui fait échouer l'action de vérification du titre (basée sur conventionnal commit)
Modifier la config de Dependabot dans le fichier `dependabot.yaml`.
On part sur "build:" d'après notre interprétation de https://github.com/angular/angular/blob/22b96b9/CONTRIBUTING.md#-commit-message-guidelines
=> build: Renommage des Pull Request générées par Dependabot pour respecter Conventionnal Commmit

front/src/routes/recherche/+page.svelte
Problème : le filtre par défaut _En présentiel_ était désélectionné lors de l'actualisation de la recherche.
Solution : sélection du filtre _En présentiel_ quand la recherche est actualisée (fonction `resetFilters()`).
https://trello.com/c/Y76POaJN/348-filtre-en-pr%C3%A9sentiel-coch%C3%A9-par-d%C3%A9faut
=> fix: sélectionne le filtre En présentiel par défaut lorsque la recherche est actualisée

back/queries/metabase/01-base/0020_mb_all_service.sql
On souhaite suivre le taux de complétion des champs déclaratifs de durée de la prestation d'un service dans Metabse.
Ces champs – `services_service.duration_weekly_hours` et `services_service.duration_weeks` – ne sont pas remontés par défaut.
1. Ajouter les champs dans la table analytique `mb_all_services` (dans le package `back/queries`).
2. Les exploiter dans Metabase, à travers une nouvelle question
A priori, pas besoin de faire une table précalculée spécifique. Metabase accepte jusqu'à 100 segments. Un segment ici correspond à 1 mois_année. 
Pour les départements, ce n'est qu'un filtre (une clause `WHERE`).
=> feat: Ajout d'un indicateur de suivi de complétion de la durée de prestation d'un service

front/src/routes/recherche/search-result.svelte
À l'époque où le bouton _Orienter votre bénéficiaire_ sur un résultat de recherche menait au formulaire Dora, il était affiché conditionnellement à l'orientabilité du service via formulaire Dora.
Depuis, le bouton a changé pour mener a la fiche service au lieu du formulaire Dora. Son affichage conditionnel ne faisait plus sens.
Cette PR affiche le bouton de façon inconditionnelle et met à jour son libellé.
=> fix: affichage inconditionnel du bouton Voir la fiche détaillée sur les résultats de recherche

front/src/lib/components/specialized/services/display/extended-service-key-informations.svelte, front/src/lib/components/specialized/services/display/service-key-informations.svelte, front/src/lib/utils/opening-hours.ts
Les horaires d’un service sont dans certains cas interprétés comme étant au format d’horaires OSM. Seulement, cela n’est pas indiqué explicitement et génère des faux horaires formatés.
Il a été décidé de supprimer ce formatage. Seul le contenu brut du champ doit être affiché.
Avant :
Après :
=> fix: suppression du formatage des horaires du service

front/src/lib/components/specialized/services/display/service-key-informations.svelte
[Ticket [256]](https://trello.com/c/0T55msku/256-fiche-services-services-di-avec-adresse-null)
Si l'adresse 1 n'est pas définie pour un service, alors l'écran affiche "null".
Ne pas afficher l'adresse (ni 1 ni 2, même si elle est définie) si l'adresse principale n'est pas définie.
Recherche : **Lille (59)** + **Équipement et alimentation**
http://localhost:3000/services/di--soliguide--62568b2e16f4f04fa2486c53?searchId=149318
=> fix(front): ne pas afficher "null" quand l'adresse principale n'est pas définie

front/src/lib/components/specialized/services/display/extended-service-key-informations.svelte, front/src/lib/components/specialized/services/display/service-key-informations.svelte, front/src/lib/utils/opening-hours.ts
Beaucoup de services DI fournissent le champ `recurrence` au format OSM. Le problème qui avait motivé la suppression de cette détection et formatage est la détection erronée du format OSM sur une valeur saisie sur un service Dora. Or, l'édition de service Dora n’offre pas de formulaire adapté pour la saisie d’horaires au format OSM.
Restauration et formatage des horaires OSM pour les services DI seulement.
Service Dora avec valeur 9h-16h auparavant erronément détectée comme étant au format OSM :
Service DI utilisant le format OSM :
=> fix: restauration de la détection et formattage des horaires OSM pour les services DI

back/dora/structures/constants.py, back/dora/structures/migrations/0073_add_label_conseil_departemental.py
**Définition** 
Un label est un regroupement de Structures, par réseau ("France Travail", "ADIE") ou typologie ("Conseil départemental", "Mission locale", "SIAE"). Avant on avait typologie et label, mais on ne s'y fie plus ,bien qu'on le laisse vivre.
**Cas d'usage**
En tant que gestionnaire, lorsque j'édite la fiche d'une structure, je peux identifier des labels nationaux grâce à une liste déroulante multi-choix.
Historiquement, ces labels étaient laissés à la main complète des utilisateurs. Avec le temps, ça a créé des soucis de doublons, de variations inappropriées ou d'incohérence. 
Un système de restriction a été mis en place (dans les [PR dora-back#353](https://github.com/gip-inclusion/dora-back/pull/353) et [dora-front#438](https://github.com/gip-inclusion/dora-front/pull/438)), …
=> feat: Supression du choix de label national "Conseil départemental"

back/requirements/base.txt
Voir : https://docs.djangoproject.com/en/5.1/releases/4.2.19/
A noter que pour la prochaine MAJ on pourrait prevoir une montée de version vers Django 5.1.x.
Absolument pas indispensable, mais ça évitera de se faire spammer par `dependabot`.
=> build: MaJ vers Django 4.2.19

analytics/models/intermediate/_intermediate_models.yml, analytics/models/intermediate/int_services_models.sql, analytics/models/staging/stg_services_models.sql
Afin de ne pas retomber dans les travers des mauvaises pratiques de metabase, [aka les multiples jointures](https://metabase.dora.inclusion.gouv.fr/question/47-liste-des-modeles-de-service-les-plus-utilises/notebook), besoin d'une table contenant les modèles de services et quelques infos de contact des structures qui les ont créées.
Création d'une `staging` isolant les modèles et d'une table `intermediate` contenant la liste des modèles et les services y étant associés.
=> feat: modèles : ajout d'une table contenant les modèles de services

.github/dependabot.yml
Tous les lundis, il y a plein de nouvelles PR de type "version upatde". Le plus souvent, il s'agit de versions mineures, qui contiennent des micro-fonctionnalités qui ne nous concernent pas ou ne nous sont pas utiles. 
Le plus souvent encore, nous faisons l'effort de regrouper ces updates au sein d'une seule et même PR front et une autre back.
Autre souci, par défaut Dependabot limite le nombre de PR ouvertes en même temps à 5 (pour le type version update).
Dependabot permet de regrouper les version updates au sein de PR uniques ([doc](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/optimizing-pr-creation-version-updates#example-4-grouped-pull-requests-for-minorpatch-updates-and-no-pull-requests-for-major-updates)).
Cette PR propose d'activer cette …
=> build(dependabot): Amélioration de la config Dependabot

front/package-lock.json, front/package.json, front/postcss.config.mjs, front/src/app.css, front/src/lib/components/display/breadcrumb.svelte, front/src/lib/components/display/dropdown-menu.svelte, front/src/lib/components/display/label.svelte, front/src/lib/components/forms/field-wrapper.svelte, front/src/lib/components/forms/fields/basic-input-field.svelte, front/src/lib/components/forms/fields/textarea-field.svelte, front/src/lib/components/inputs/obsolete/select-field.svelte, front/src/lib/components/inputs/opening-hours/days-grid.svelte, front/src/lib/components/inputs/radio-buttons.svelte, front/src/lib/components/inputs/select/simple-autocomplete.svelte, front/src/lib/components/specialized/favorite-icon.svelte, front/src/lib/components/specialized/service-search.svelte, front/src/lib/components/specialized/tally-popup.svelte, front/src/routes/(modeles-services)/_common/service-description.svelte, front/vite.config.ts
Correction des plantages de `npm run dev` suite à la mise a niveau de Tailwind CSS version la version 4 (#220).
- Utilisation de _@tailwincss/vite_ au lieu de _@tailwindcss/postcss_ ;
- Suppression de la classe Tailwind CSS invalide `min-w-[${minWidth}]` et de la prop `minWidth` inutilisée dans `DropdownMenu` ;
- Conversion des classes Tailwind CSS problématiques (contenant généralement un caractère `:`, `/` ou `!`) dans les directives `@apply` ;
- Remplacement des variables `--s*` par les variables `--spacing-s*` ( faisait doublon).
Je n'ai plus constaté de plantages avec ces modifications. Il y a peut-être des corrections qui occasionnent des différences de rendu, mais je n'en ai pas constaté.
=> fix(tailwind): correction des plantages dûs à la mise à niveau de Tailwind CSS

analytics/.env.example, analytics/sync-analytics.sh
Le script `sync-analytics.sh` nécessite la définition des variables d'environnement `DORA_DATABASE_URL` et `DATABASE_URL`.
Cette PR ajoute un fichier `.env.example` avec ces variables d'environnement et modifie le script `sync-analytics.sh` pour qu'il lise et vérifie ces variables.
=> feat(analytics): utilisation d'un fichier .env pour le chargement des variables d'environnement analytics

front/src/routes/+page.svelte
On souhaite disposer d'un moyen simple et visible depuis la page d'accueil pour accéder à la nouvelle page expérimentale de recherche de solutions d'insertion par mots-clés.
On met un gros bouton-lien CTA-like sous le formulaire standard qui redirige vers la page `/recherche-textuelle`.
On conditionne l'affichage de ce bouton-lien à la définition de la variable d'environnement `VITE_GOOGLE_CSE_ID`, côté front.
Pour le tracking web analytics via Matomo, on prend le parti de faire un trigger de type "element click" basé sur le libellé du lien "Rechercher par mots-clés".
=> feat(search): Ajout d'un Button-Lien vers la page de recherche textuelle

front/src/lib/components/specialized/establishment-search/search-by-commune.svelte, front/src/routes/+layout.svelte, front/src/routes/_index/footer.svelte, front/src/routes/_index/menu-mon-compte.svelte, front/src/routes/_index/sub-menu.svelte, front/src/routes/mes-alertes/+page.svelte, front/src/routes/structures/[slug]/empty-notice.svelte
En explorant la migration de Svelte v4 à v5, des warnings d'accessibilité apparaissent dans la console. Autant les régler en amont.
Correction des règles :
1. Ne pas préciser de rôle "main" pour une balise `<main>`
2. Toujours spécifier la valeur "true" pour les propriétés `aria-hidden`.
3. Ne pas préciser de rôle "contentinfo" pour une balise <footer>
=> fix(a11y): Correction de warnings d'accessibilité

front/svelte.config.js
La page [/stats](https://dora.inclusion.beta.gouv.fr/stats) intègre un dashboard Metabase publique. Celui-ci ne s'affiche plus depuis quelques jours.
Ajouter une CSP de type `frame-src` pour le domaine https://metabase.dora.inclusion.beta.gouv.fr.
=> fix(stats): Problème d'affichage du dashboard Metabase dans la page /stats

front/svelte.config.js
Suite à l'ajout de Google Search (Google CSE), pour l'expérimentation de recherche par mots-clés (cf. [/recherche-textuelle](https://dora.inclusion.beta.gouv.fr/recherche-textuelle)), nous avons déclaré la catégorie `frame-src` dans les CSP côté front-end.
Cela nous oblige à déclarer toutes les sources de ressources chargées dans des iframes.
Cela a créé des soucis d'affichage de tableau de bord (Metabase) (déjà fixé). Il reste des soucis d'affichage de vidéos (sur tube.numerique.gouv.fr) et de formulaires Tally (sur tally.so)
Ajouter les CSP["frame-src"] manquantes.
=> fix(front): Correction des problèmes de CSP

back/dora/data_inclusion/client.py
Les services D·I dont le lien est cassé sont correctement interceptés et affichés comme inaccessibles.
Auparavant une erreur empêchait la liste des autres favoris de s'afficher si un des favoris était en erreur.
À la charge de l'utilisateur de les supprimer dans sa liste de favoris.
=> fix: évite une erreur lors de la récupération des favoris

analytics/sync-analytics.sh
Impossible de dumper depuis la montée en version à postgres 16 sur la db car le script de synchro force l'utilisation de postgres 15.
Retrait de la condition
=> fix: retrait de la version de postgres hardcodée dans le script de synchro

analytics/sync-analytics.sh
Nous avons une instance de Metabase (MB) qui nous sert à faire de l'exploration et de l'analyse de données, afin d'améliorer le produit, connaître nos usagers et le marché, et avoir un "pilotage par l'impact" du projet. 
Ce MB s'appuie sur une base de données obtenue à partir de la base de production, certaines tables étant recopiées (certains champs étant ignorés ou anonymisés) et d'autres étant pre-construites ou déduites (tables dites "intermediate" et "staging"). 
Pour augmenter notre capacité d'exploitation de la donnée récoltée / produite dans DORA, nous aimerions recouper les informations et les manipuler avec celles concernant les services et structures de data·inclusion.
A noter que la mise à jour de la "base analytics" et la synchronisation depuis la base de production de DORA …
=> feat(data): Ajout des données Services et Structures de data•inclusion à la base analytics de DORA

front/src/routes/admin/structures/structures-map.svelte
La géométrie du département est simplifiée sur le back-end dans le  `DeptSerializer`. Dans le cas de certains départements, la simplification est trop importante et on n'a plus de coordonnées.
En attendant de corriger proprement ce problème côté back-end, je gère le cas où on n'a pas de coordonnées côté front-end pour éviter un plantage.
=> fix: zoomToStructures() : gère le cas où coordinates est vide

analytics/models/_sources.yml
Pour permettre d'ajouter un indicateur sur les motifs de refus des orientations sur les services financés.
=> feat(data): ajout des tables contenant les motifs de refus des orientations

back/dora/data_inclusion/client.py, back/dora/data_inclusion/test_utils.py, back/dora/services/tests/test_services.py, back/dora/services/views.py, front/src/lib/requests/services.ts, front/src/lib/utils/misc.ts, front/src/lib/utils/stats.ts
Afin de permettre à DI de reconnaître les lectures de service faites par des robots, on passe le User-Agent et le _user hash_ (utilisé pour identifier un utilisateur anonyme) en par headers HTTP à la route `/api/v0/services/{source}/{id}`.
Ces informations ne sont accessibles que lorsque l'appel est fait depuis le client et pas depuis le serveur en mode SSR.
=> feat: envoi du user agent et du user hash à DI lors de la récupération d'un service

back/dora/core/views.py, back/dora/orientations/management/commands/delete_orientation_attachments.py, back/dora/orientations/models.py, back/dora/orientations/tests/test_orientation_attachments.py
Ajoute des éléments au modèle `Orientation` pour permettre la destruction des pièces-jointes attachées (stockées sur un S3 Clevercloud) :
- directement lors de la suppression de l'orientation,
- via une management-command `delete_orientation_attachments` prenant la pk de l'orientation en paramètre (si on ne souhaite pas supprimer l'orientation).
Les tests unitaires sont "skippés"  pour la CI car elle ne dispose pas de S3 pour des tests e2e.
Ils sont utilisables sur un environnement de dev avec un S3 local (Minio)
=> feat(sécu): suppression des pièces-jointes d'une orientation

back/dora/logs/__init__.py, back/dora/logs/admin.py, back/dora/oidc/backends.py
- En base de données via un logger spécifique,
- à chaque connexion ProConnect 
- on sait si l'utilisateur est un gestionnaire de territoire
- et si il est administrateur de structure *sans plus de précision*
---
- **fix: accès plus simple au logger**
- **fix: recherche par le message du log**
- **feat: logging de la connexion ProConnect des utilisateurs**
- **fix: traçage de la connexion des managers**
=> feat(sécu): traçage de la connexion des utilisateurs

back/dora/orientations/templates/orientation-rejected-prescriber.mjml, back/dora/orientations/templates/orientation-rejected-structure.mjml
=> fix: réduit l'espace au-dessus du CTA des mails d'orientation rejetée

front/src/lib/utils/current-structure.ts, front/src/routes/(modeles-services)/components/service-body/service-presentation/service-key-informations/service-key-informations.svelte, front/src/routes/(modeles-services)/components/service-body/service-presentation/service-presentation.svelte, front/src/routes/(modeles-services)/services/[slug]/+page.svelte, front/src/routes/(modeles-services)/services/[slug]/service-feedback-button.svelte, front/src/routes/(modeles-services)/services/[slug]/service-update-date.svelte
Sur une fiche service, le bouton est situé à 3 endroits différents de la page.
- Ajout d'une fonction utilitaire `isMemberOrPotentielMemberOfStructure()` ;
- Utilisation de _setContext()_ et _getContext()_ pour transmettre le statut d'affichage à tous les boutons en évitant le _prop drilling_ ;
- Affichage du bouton et de la modale pour tout le monde sauf pour les membres et membres potentiels de la structure du service.
=> feat: affiche le bouton et la modale de signalement pour tout le monde sauf pour les membres et membres potentiels de la structure du service

.talismanrc, back/.talismanrc, back/README.md, back/docker-compose.yml.template
Après avoir installé le projet, j'ai remarqué que quelques consignes sont manquantes. Ce PR les ajoute.
À noter :
- il fallait aussi ajouter/modifier deux choses dans `docker-compose.yml` donc j'ai fait ça aussi
- j'ai eu besoin de mettre `.tailsmanrc` à la racine du projet pour faire un commit
=> docs: ajouter des consignes manquantes au ReadMe

back/dora/services/management/commands/import_services.py, back/dora/services/models.py, back/dora/services/tests/test_import_services.py, back/dora/services/utils.py
[Ticket](https://www.notion.so/gip-inclusion/Cr-ation-de-services-par-import-services-sont-en-brouillon-si-certaines-infos-sont-manquantes-2095f321b6048033b69ec6837ce52abe?source=copy_link)
Quand certaines colonnes optionnelles du csv d'import sont manquantes, les services peuvent être crées mais ils sont mis en brouillon. (Les conditions sont dans le ticket au-dessus)
* Pour que la colonne `diffusion_zone_type` soit optionnelle, il faut mettre `""` comme valeur si cette colonne n'est pas remplie dans le csv. j'ai supprimé la verification d'une valeur manquante pour cette colonne.
* Ajout d'une colonne `is_contact_info_public` (le défaut est `False`)
* la colonne `is_draft` a été supprimée dans une migration précédente donc j'ai enlevé l'un des vestiges de cette propriété dans ce PR aussi
=> feat: créer des services en brouillon quand certaines infos sont manquantes

back/dora/services/management/commands/import_services.py, back/dora/services/tests/test_import_services.py
le csv template pour l'import des nouveaux services utilisent les `values` des `AdminDivisionType` (`city`, `epci`, etc) mais le script actuel vérifie les label (`Commune`, etc). Ce PR fait en sorte que le script vérifie la `value` au lieu du `label`.
=> fix: utiliser value de diffusion_zone_type au lieu de label

analytics/cron.json, analytics/models/_sources.yml, analytics/sync-matomo.py
🌼 Objectif
Récupérer les événements de clic sur partage de la fiche service afin de suivre l'usage sur metabase.
🌸 Comment
Création d'un modèle python dans dbt dont le but est de récupérer ces infos via l'API Matomo.
On récupère tous les événements de type souhaité (catégorie "PageService" et action "Clic Bouton Envoyer la Fiche" ou "Clic Bouton Partager cette Fiche" ou "Clic Bouton Profil Professionnel". 
Les événements de clic partage et d'envoi de fiche sont conservés, et le clic bouton professionnel est comptabilisé pour enregistrer lors de l'envoi de la fiche, si c'est envoyé à un pro (nombre impair de clics) ou à un bénéficiaire (nombre pair) 
-> tricky mais matomo ne permet pas de suivre quel bouton a été cliqué, donc obligé de passer par un compteur. Un cas à la marge n'est pas …
=> feat(data): import des données de partage de fiche service depuis matomo

back/dora/notifications/tasks/tests/tests_users.py, back/dora/notifications/tasks/users.py, back/dora/users/emails.py
Les structures obsolètes ne doivent pas être prises en compte pour les notifications aux gestionnaires de territoire.
_Ni pour quoi que ce soit, d'ailleurs._
Elles sont désormais filtrées dans le cadre des notifications (uniquement).
=> fix: les structures obsolètes doivent être exclues des notifications de modération

back/dora/services/admin.py, back/dora/services/tests/test_admin_import_view.py
Pour l'import des services dans l'admin, on affiche ce message d'erreur quand il y a des erreurs bloquantes et c'est un vrai import : 
Quand il y a des avertissements pendant un vrai import et il y a des erreurs bloquantes, on supprime `Import réalisé` dans le titre comme ici :
=> feat: changer les messages d'erreur/avertissement

back/dora/services/admin.py, back/dora/services/tests/test_admin_import_view.py, back/dora/static/admin/css/import_form.css
Pour que les utilisateurs sachent que les avertissements sont uniquement pour montrer ce que l'import donnerait, j'ai ajouté un nouveau message montré ci-dessous. Ce message ne s'affiche que quand c'est un vrai import et il y a des erreurs bloquantes et il y a des avertissements 
En plus, on change l'avertissements des services qui seront créés en brouillon quand c'est un vrai import et il y a des erreurs bloquants.
=> feat: ajouter un message pour clarifier que les avertissements sont à titre informatif quand il y a des erreurs bloquantes

back/dora/services/csv_import.py, back/dora/services/tests/test_import_services.py
Pour l'import des services, si l'utilisateur fait un import de test sans saisir un label, une source sera créée en base. C'est problématique parce que le db exige unicité des valeurs de `ServiceSource`. Si l'utilisateur ressaie avec un autre label, il y aura une erreur bloquante. 
Ce PR permet des tests sans créer une source pour que l'utilisateur puisse tester sans saisir le label. Dès que tout est bon, il peut saisir son label et executer l'import sans souci.
=> fix: permettre un source label non-unique quand c'est un test run

back/dora/services/csv_import.py, back/dora/services/tests/test_import_services.py
Si un service qui est importé est éligible d'être publié, il faut que la valeur de la date de publication soit pas `null`. 
Ce PR fait en sorte que la date de publication soit correcte mais que les services en brouillon n'aient pas de date de publication
=> fix: ajouter une date de publication si le service importé est publié

analytics/models/intermediate/int_orientation_user_service.sql, analytics/models/staging/stg_mobilisationevent.sql, analytics/models/staging/stg_orientation.sql, analytics/models/staging/stg_pageview.sql, analytics/models/staging/stg_searchview.sql, analytics/models/staging/stg_serviceview.sql
Certaines iMER n'étaient pas ajoutées à la table iMER pour plusieurs raisons :
- `prescriber_id` inexistant : sans doute des utilisateurs supprimés (marginal, mais gardons les :))
- `service_id` inexistant : correspond aux services importés de d·i, qui ont un `di_service_id` (majorité des cas!)
- `service_id` inexistant dans la table `int_service_structure` : services non rattachés à une structure (marginal mais gardons les !)
Modification de la jointure en conséquence, afin de garder toutes les orientations (commit [878b1f2](https://github.com/gip-inclusion/dora/pull/455/commits/878b1f22d5209311a09c36db9cf2651793d36cc0))
La table sera incomplète pour les informations de user ou de structure pour les services concernés, ce qui n'est pas problématique et sera géré sur metabase.
J'en …
=> fix: correction des iMER manquantes 🌸

back/dora/core/test_utils.py, back/dora/orientations/tests/conftest.py, back/dora/orientations/tests/test_orientation_endpoints.py, back/dora/orientations/views.py
Lors de l'acceptation d'une orientation, l'objet service associé à l'orientation est accédé. Or, il n'existe pas pour les services DI, provoquant une erreur. Ce correctif vérifie son existence avant d'y accéder. Un test a été ajouté.
=> fix: acceptation d'une orientation vers un service DI

back/requirements/base.txt
Test :
1. activer la 2FA avec la variable d'environnement `DJANGO_ADMIN_2FA_ENABLED=true` ;
2. aller sur django-admin ;
3. créer un _TOTP device_ ;
4. cliquer sur le lien _qrcode_ ;
5. un code QR doit s'afficher.
=> feat: ajout du package segno pour la génération du code QR de configuration du OTP

back/dora/oidc/backends.py
On permet la connexion si le sub est différent de celui enregistré à condition que l'adresse e-mail soit la même.
On logue les cas où le sub est différent pour analyse postérieure.
=> fix: connexion ProConnect avec sub différent

front/src/routes/(modeles-services)/modeles/[slug]/+page.ts
Corrige https://inclusion.sentry.io/issues/53882782/?environment=production&project=4509599011045456&query=is%3Aunresolved&referrer=issue-stream
=> fix: renvoie une erreur 404 si le modèle n'est pas trouvé

front/package-lock.json, front/package.json, front/src/lib/components/display/markdown-renderer.svelte, front/src/lib/components/display/static-markdown.svelte, front/src/lib/components/display/text-clamp.svelte, front/src/lib/components/inputs/select/simple-autocomplete.svelte, front/src/lib/components/specialized/services/field-model.svelte, front/src/routes/admin/contributions/line.svelte, front/src/routes/admin/contributions/suggestion-modal.svelte
Utilisation de `@html` dans deux fichiers uniquement :
- MardownRenderer qui centralise l'affichage du rendu Markdown ;
- SimpleAutocomplete pour le _highlighting_.
Dans les deux cas, `insane()` est utilisé pour sécuriser le HTML.
=> chore: centralisation du Markdown avec @html dans un seul composant

back/config/settings/base.py, back/config/settings/test.py
Pour mieux protéger la sécurité de l'app, ce PR ajoute une limitation du débit pour empêcher des attaques qui cherchent à spammer l'app. On s'appuie sur le throttling de Django qui utilise la cache redis déjà mise en place. Ça nous permet de verifier la limitation à travers nos deux conteneurs Scalingo.
=> chore: ajouter la limitation du debit

front/src/lib/components/specialized/service-search.svelte, front/src/routes/(modeles-services)/components/service-body/service-presentation/service-key-informations/service-key-informations.svelte
Il y a deux erreurs remontées dans Sentry qui viennent d'une propriété accédée d'une valeur `null`. Ce PR règle ces deux soucis en utilisant optional chaining
=> fix: empêcher les erreurs de null property remontées dans Sentry

front/src/lib/components/specialized/services/set-as-updated-modal.svelte, front/src/routes/(modeles-services)/services/[slug]/+page.svelte, front/src/routes/(modeles-services)/services/[slug]/service-toolbar.svelte, front/src/routes/(modeles-services)/services/[slug]/service-update-buttons.svelte, front/src/routes/(modeles-services)/services/[slug]/service-update-date.svelte
Le problème était dû à `data = $bindable()` dans `+page.svelte` qui ne suffisait pas à rendre la variable `data` réactive. En utilisant `$state()`, on en crée une copie réactive.
J'ai profité de ce changement pour faire quelques corrections de typage et utiliser une espace insécable.
=> fix: Fiche service : le clic sur « Marquer comme à jour » provoque la mise à jour du libellé d'actualisation

front/package-lock.json, front/package.json
Concerne l'alerte de sécurité https://github.com/gip-inclusion/dora/security/dependabot/2
On doit forcer la mise à jour (override) car SvelteKit de peut pas se permettre de mettre à jour _cookie_ avant sa version v3 car la version 0.7.0 de _cookie_ comporte un breaking change. Celui-ci ne nous concerne pas et on peut donc forcer la mise à jour et ainsi éliminer la vulnérabilité et l'alerte de sécurité.
Voir : https://github.com/sveltejs/kit/pull/12767
=> fix: mise à jour forcée de cookie pour cause de vulnérabilité

back/dora/services/csv_import.py
Ce PR fait trois fixes pour l'import des services quand il est lancé dans le terminal comme commande django:
1. la console dit `Dry run` même si c'est une production run
2. les headers manquants n'ont pas été affichés et la commande termine silencieusement. 
3. La sortie à la fin est un peu confus
a. Le nombre de services qui manquent la géolocalisation doit être à côte de la détail
b. Le nombre de doublons doit être précise comme `potentiellement dupliqué`
=> fix: trois fixs pour l'import des services

analytics/sync-analytics.sh, analytics/sync-matomo.py
1) changer la table de schema, car on drop toutes les tables de public dans sync-analytics
2) exclure la table dans le pg_restore pour éviter de la drop sans la recréer
=> fix: stop erasing mtm table with sync-analytics (:

back/dora/services/csv_import.py, back/dora/services/migrations/0125_correct_diffusion_zone_details.py, back/dora/services/tests/test_import_services.py
On a vu un bug où les services importés avec un diffusion_zone_type de département ne sont pas apparus sur une recherche dans une zone pertinente. Un bon exemple est ce [service](https://dora.inclusion.beta.gouv.fr/services/caisse-primaire-assu-rovg--lxwe) de santé à Poissy qui n'apparait pas pour des recherches des services de santé à Poissy comme celui-ci /search/?cats=sante&city=78498&cl=Poissy%20(78)&l=Poissy%20(78)
Le problème est que pour les services ajouté par l'import on met toujours le city_code pour les diffusion_zone_details sans prendre compte de la diffusion_zone_type comme vu [ici](https://github.com/gip-inclusion/dora/blob/89fd9bfdcb214b6af9013efca0722612ef362c4c/back/dora/services/csv_import.py#L286)
Ce PR fait une migration pour corriger les services dont les …
=> fix: corriger diffusion zone details pour services importes

back/dora/structures/templates/notification-service-activation.mjml, front/src/routes/(static)/nos-partenaires/+page.svelte, front/src/routes/+page.svelte
Il y a deux endroits où le nombre de structures référencés est affiché. Ce PR change les deux pour montrer 23 000
=> feat: changer le nombre de structures listé sur le site

front/src/lib/requests/services.ts, front/src/lib/utils/choice.ts, front/src/routes/(modeles-services)/components/service-body/service-presentation/service-key-informations/service-key-informations.svelte, front/src/routes/(modeles-services)/services/[slug]/+page.svelte
**Problème :** la fonction `getServicesOptions()` retourne `null` en cas d'échec de l'appel. Or, le code appelant ne gère pas ce cas, occasionnant de nombreuses erreurs `Cannot read properties of undefined/null**`.
**Solution :** on gère l'échec au plus tôt et on lève une exception avec le message d'erreur. Elle sera remontée sur Sentry à la place de toutes les autres erreurs `Cannot read properties of undefined/null`.
=> Échec explicite lorsque que /services-options/ ne retourne pas de données

back/config/settings/base.py
Pour améliorer l'UX, ce PR augmente le nombre de requêtes permis pour des utilisateurs non connectés. La limitation du débit pour les utilisateurs connectés et non-connectés sont aussi configurables par deux env vars pour plus facilement les modifier dans l'avenir.
=> fix: augmenter la limite des requêtes pour les utilisateurs pas connectés
