gip-inclusion/dora

back/envs-example/dev.env

Mise à jour avec la nouvelle URL du serveur DI staging.

envs-example/dev.env: mise à jour de DATA_INCLUSION_URL

---

docs/adr/002-architecture-label-financement.md

Architecture simple avec implémentation _back-end_.
Quelques différences UX par rapport à l'expérimentation purement _front-end_.

ADR sur les labels de financement

---

back/requirements/base.txt
back/requirements/dev.txt

libs: MaJ dépendances back

---

back/config/settings/base.py
back/dora/oidc/views.py

En cas d'expiration de la session Django lors d'une connexion par lien
direct.

fix: correction d'une erreur de redirection

---

front/src/routes/(static)/cgu/cgu-20240506/+page.svelte
front/src/routes/(static)/cgu/cgu-20240506/+page.ts
front/src/routes/(static)/cgu/cgu-20240506/content.md
front/src/routes/(static)/cgu/cgu-20240506/md/+server.ts
front/src/routes/(static)/cgu/version.ts

docs(cgu): Mise à jour des CGU DORA

---

front/src/lib/utils/misc.ts
front/src/tests/utils/misc/formatPhoneNumber.test.ts

https://trello.com/c/QaUAHHKJ/325-format-numero-de-tel

fix: Correction de la fonction de formattage de numéro de téléphone + tests

---

back/requirements/base.txt
back/requirements/test.txt

Montée de version mineures de : 
* **model-bakery**
* **psycopg**
* **yachalk**
* **ruff**

build: Montée de version de dépendances back-end

---

back/requirements/dev.txt
docs/models/README.md

Essentiellement pour mettre à disposition un lien public pour l'AIPD.

feat(doc): ajout d'un export PNG de la modélisation Django

---

back/dora/services/emails.py
back/dora/services/templates/notification-services.mjml
back/scripts/email_service_brouillon_mednum.py

voir : https://www.notion.so/gip-inclusion/1915f321b60480d68b7fee165b290b43?v=1915f321b60480b1a050000c9fb68230&p=1a05f321b60480ea9e27cb8d3c40ecd8&pm=s
Ce script "one-shot" envoie un e-mail aux admins de structures ayant des
services MEDNUM en brouillon.

feat: ajout d'un script de notification pour les services MEDNUM

---

back/requirements/base.txt

Voir :
https://www.djangoproject.com/weblog/2025/mar/06/security-releases/

build: Maj vers Django 4.2.20

---

front/src/routes/(modeles-services)/components/service-body/service-presentation/service-key-informations/service-key-informations.svelte
front/src/routes/(modeles-services)/components/service-body/service-presentation/service-steps.svelte

- Affichage du texte Vous etes un particulier ? avec le lien vers la structure uniquement en mode non-connecté ;
- Utilisation de OpenStreetMap Nominatim pour avoir le pointeur de lieu.

fix: correctifs redesign fiche service

---

back/scripts/import_siaes.py

Ajoute le label `siae` aux structures passées en paramètre (un fichier avec un numéro de SIRET par ligne).

feat: script de labellisation des SIAE

---

front/src/app.css
front/src/routes/admin/structures/filters.svelte

Ajout du _s_ manquant à _Structures référencée_.
Configuration d'une largeur max au tooltip.

fix(tdb): correctifs tableau de bord gestionnaire

---

front/src/routes/(modeles-services)/components/service-body/service-presentation/service-di-identification.svelte
front/src/routes/(modeles-services)/components/service-body/service-presentation/service-presentation.svelte

Utilisables pour désactiver le formulaire Dora pour la structure concernée.

feat(service): ajout d'informations de structure DI (source et identifiant) sur les fiches service DI si l'utilisateur est staff

---

back/requirements/base.txt

Voir https://github.com/gip-inclusion/dora/pull/313#issuecomment-2769432864

fix: downgrade djangorestframework à 15.2.0

---

.github/workflows/create-review-apps.yml

Renommage de `SCALINGO_API_TOKEN` en `SCALINGO_CLI_TOKEN` comme fait pour l'autre script.

build: create-review-apps.yml: renommage variable env Scalingo

---

back/dora/notifications/migrations/0001_initial.py
back/dora/notifications/migrations/0002_remove_notification_check_structure_and_more.py
back/dora/notifications/models.py
back/dora/oidc/tests/test_sessions.py
back/dora/orientations/migrations/0010_orientation_check_valid_service.py
back/dora/orientations/models.py
back/dora/services/migrations/0054_service_status_and_more.py
back/dora/services/models.py
back/dora/structures/migrations/0039_auto_20220315_1808.py
back/dora/structures/migrations/0042_auto_20220323_1850.py
back/dora/structures/models.py
back/pyproject.toml
back/requirements/base.txt

- **build(libs): Maj des libs pour Django 5.2**
- **fix: corrige des warnings de déprecation pour Django 6**
- **fix: ignore les warnings du à `josepy`**
- **fix: ignore les warnings concernant l'utilisation des `staticfiles`**

feat: migration vers Django v5.2

---

front/src/routes/(static)/politique-de-confidentialite/content.md

feat(politique de confidentialité): mention de l'identifiant unique France Travail

---

front/src/lib/consts.ts
front/src/lib/types.ts
front/src/routes/admin/structures/+page.svelte
front/src/routes/admin/structures/+page.ts

feat(TDB GT): mise à jour des liens de suivi de statistiques

---

analytics/sync-matomo.py

Dernière petite correction pour faire marcher la synchro matomo/metabase !

fix: replace postgres with postgresql to solve error

---

front/src/lib/components/display/dropdown-menu.svelte
front/src/routes/_index/menu-aide.svelte
front/src/routes/_index/menu-mes-structures.svelte
front/src/routes/_index/menu-mon-compte.svelte
front/src/routes/_index/menu.svelte
front/src/routes/_index/sub-menu.svelte

feat: refonte du header

---

analytics/sync-analytics.sh

Suppression d'une condition qui plante et donc ne restaure pas la db après suppression :D

fix: delete the wrong condition
